name: htsm-dms
services:
  api:
    restart: always
    image: htsm-dms-api:latest
    build: .
    container_name: htsm-dms
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/htsm-dms
      - IFLYTEK_OCR_APPID=6e751b44
      - IFLYTEK_OCR_API_KEY=52078ebea274a1a4b7fe9f843019bac1
      - IFLYTEK_OCR_API_SECRET=YzA3OTMzN2I0ODFhODYzYzYzMDUxZTBm
      - IFLYTEK_OCR_PATH=/v1/private/sf8e6aca1
      - KGD_API_BASE_URL=http://192.168.110.100:3001
      - KGD_API_KEY=7aa6aa6cacc3c3574873f1c5f95b001e4094ebfe2bcce36ac71553ade1385c74
    volumes:
      - ./data:/app/data
    depends_on:
      - mongo
  mongo:
    restart: always
    image: mongo:6
    container_name: htsm-dms-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
